#pragma once
#include "IsohypseData.h"
#include "Scene/Generation/OmnigenGenerationData.h"
#include "Scene/Generation/Stages/Layout/DomainDrawable.h"
#include "Utils/CircularVectorView.h"

class DRidgeMarker;
class IHHeightGraphNode;
class IHHeightGraphEdge;

namespace tml
{
    template<typename COOR_TYPE, typename DATA_TYPE> class qtree;
}

class ContourLines
{
    struct IsohypseMergeInfo
    {
        // One pair is a range on one IH
        std::pair<int, int> mergeBounds1, mergeBounds2;
        std::pair<int, int> shrinkBounds1, shrinkBounds2;
        float distance;
    };

    struct IHProtoTreeData
    {
        int hullIdx;
        int i0;
        int i1;
    };

    struct IHHeightBoundNodeData
    {
        int id;
        int height;
        qint64 originObject;
        Generation::HeightBoundOrigin originType;
        std::unordered_set<qint64> domains;
        std::vector<Segment2D> segments;
    };

    struct IHHeightBoundNode
    {
        std::vector<IHHeightBoundNodeData> bounds;
    };

    struct RidgelineDirection
    {
        bool ridgeForwardDirection;
        int prevPointIdx;
        int nextPointIdx;
        QVector3D intersectionOnHull;
        std::unordered_map<QVector3D /*source point*/, std::pair<std::vector<QVector3D> /*ridge shape*/, qint64 /*ridge id*/>> ridgelinePoints;
    };

public:
    ContourLines() = delete;

    // Generation constants and variables
    static const inline float baseIncrement = 200.0f;
    static const inline float fixedHeightIncrement = 200.0f;
    static inline QStack<IHProtoData> ihStack;

    // Creates IH stack. IHs are generated by taking them off the top of the stack, to ensure higher ones are generated first.
    // Will also generate IH stubs (lvls 0 & 1)
    static void prepareStack();

    // Used when some IHs already exist
    static void regenerateStack();

    // Grow IHs until they cover entire level
    static bool generate();

    // Compute placement for a new IH point originating from src. Assumes CW ordering.
    static QVector3D generateNewHullPoint(const GVector2D& prev, const GVector2D& src, const GVector2D& next, float increment);

    // Preflow for a given IH point ("P") is a set of points form parent IHs, for which "P" is the nearest descendant
    static void computePreflow();

    static std::map<quint64, float> findLocalMinPerDomain(const std::vector<QSharedPointer<DRidgeMarker>>& ridgeRoots);

private:
    static QMultiMap<float, IHProtoData> generateLevels0And1(const std::vector<QSharedPointer<DRidgeMarker>>& ridgeRoots, const std::map<qint64, std::map<Generation::HeightBoundOrigin, std::map<qint64, std::map<int, std::vector<Segment2D>>>>>& heightBounds);

    static float randomIncrement(std::vector<QVector3D>* newHull, const std::vector<QVector3D>* oldHull, const QSharedPointer<Isohypse>* sourceMarkers, const int i, const float baseIncrement, const float baseIncrementValue, const int levelIdx, int extremeDeviations);

    // Add noise to long straight segments so they look more natural
    static void breakStraightLines(std::vector<QVector3D>* newHull, const std::vector<QVector3D>* oldHull, const float baseIncrement, const QQuaternion* rotateLeft90);
    static QVector4D getColorByLevelAndHeight(int level, float height);
    static bool isRidgeInsideBound(const std::vector<QVector3D>& ridgePoints, const std::vector<QVector3D>& boundPoints);
    static void correctSwallowedIHHeights(const std::set<IHProtoData*>& ihDataToCorrect, const std::set<Isohypse*>& ihsToCorrect, float currentH, std::vector<IHProtoData>* ihProtoData);

    // Handle cases where an IH ended up being wholly inside another IH after some growth / merge phase
    static void swallowAll(std::vector<IHProtoData>* ihProtoData);

    static float distanceToHeightStepsScalling(const IHProtoData& data, float increment, float targetDistance, float targetHeight);
    static float computeDistanceStepsProjection(float increment, float targetDistance);

    // Peak finding
    static std::unordered_multimap<float, std::vector<QVector3D>> findPeaks(const QSharedPointer<DRidgeMarker>& ridge, const std::set<std::vector<QVector3D>>& peakMap);
    static std::vector<QVector3D> checkSubridgeForAdditionalPeakPoints(const QSharedPointer<DRidgeMarker>& subridge, const float peakHeight, const float peakMargin);

    // Height-bounds
    static float computeIncrement(const std::vector<QVector3D>& oldHull, const std::vector<QVector3D>& projectedHull, const std::vector<float>& projectedIncrements, int i, IHProtoData* currentData, const std::map<qint64, std::map<Generation::HeightBoundOrigin, std::map<qint64, std::map<int, std::vector<Segment2D>>>>>& heightBounds, float slopeAngle);
    static QSharedPointer<tml::qtree<float, IHHeightBoundNode>> computeHeightBoundsQtree(const std::map<qint64, std::map<Generation::HeightBoundOrigin, std::map<qint64, std::map<int, std::vector<Segment2D>>>>>& heightBounds);

    // Height-based gen
    static std::array<std::vector<IHProtoData>, 2> chooseIhsToGrow();
    static QMultiMap<float, IHProtoData> generateNextIHs(const std::vector<IHProtoData>& sourceIhs, std::vector<IHProtoData>* otherIhs, const std::map<qint64, std::map<Generation::HeightBoundOrigin, std::map<qint64, std::map<int, std::vector<Segment2D>>>>>& heightBounds, int level);
    static QVector3D findIHPeak(const IHProtoData& data, int id);
    static void removeIHs(std::vector<IHProtoData>* ihProtoData, const std::vector<int>& ids);
    static quint64 findDomainBetweenIsohypses(const IHSrcInfo& data1, const IHSrcInfo& data2, const QVector3D& point);
    static float findSlopeAngleBetweenRidges(const IHProtoData& data1, const IHProtoData& data2, const QSharedPointer<DDomain>& domain);
    static QSharedPointer<tml::qtree<float, IHProtoTreeData>> computeProtoDataQtree(const std::vector<IHProtoData>& ihProtoData);

    // Isohypse merging
    static void mergeNextIHs(std::vector<IHProtoData>* ihProtoData);
    static std::vector<std::pair<std::pair<int, int>, IsohypseMergeInfo>> detectClosestIsohypseColissions(const std::vector<IHProtoData>& ihProtoData);
    static std::optional<IsohypseMergeInfo> detectClosestIsohypseInfo(const IHProtoData& ih1, const IHProtoData& ih2);
    static std::optional<float> computeValleyWidth(IHProtoData* ihData1, IHProtoData* ihData2, const IsohypseMergeInfo& mergeInfo);
    static IHProtoData createMergedIH(const IHProtoData& ih1, const IHProtoData& ih2, const std::pair<int, int>& mergePts1, const std::pair<int, int>& mergePts2);
    static bool mergeCancelShrinkIsohypse(IHProtoData* data1, const std::pair<int, int>& segmentToShrink1, IHProtoData* data2, const std::pair<int, int>& segmentToShrink2, float minDistRequired, bool shrinkSecondSegment = true);

    // Isohypse modification / fixing
    static bool fixHull(IHProtoData* data, const std::vector<std::vector<QVector3D>>& oldHulls = {}, bool omitThicken = false);
    static void thickenHull(IHProtoData* data);
    static void findAndDeleteDuplicatePoints(IHProtoData* data);
    static void findAndDeleteLoopsOfHull(IHProtoData* data);
    static void modifySegmentByValue(IHProtoData* data, const IHProtoData& oldData, const std::pair<int, int>& segment, const float modifyValue, const bool tendency);
    static void findAndModifySegments(IHProtoData* data, const IHProtoData& oldData);
    static bool checkFlatlandsAgainstOthers(const std::vector<IHProtoData>& allData);
    static void modifyPointsAccordingToOldHulls(IHProtoData* data, const std::vector<std::vector<QVector3D>>& oldHulls);

    // Isohypse modification according to ridgeline
    static std::unordered_map<QVector3D, std::pair<std::vector<QVector3D>, qint64>> findRidgePoints(const QSharedPointer<DRidgeMarker>& intersectionRidge, const QVector3D& intersectionPoint, const float height, int firstIdx, bool isForwardDirection);
    static std::vector<RidgelineDirection> checkForIntersectionWithRidge(const std::unordered_set<qint64>& rootRidges, const std::vector<QVector3D>& currentHull, const float height);
    static void reshapeHullToRidgeline(const std::vector<RidgelineDirection>& intersectionData, IHProtoData* data);
    static std::vector<std::tuple<QVector3D /* new point*/, float /*slope factor*/, QVector3D /*ridge source point*/>> getHullSectionFromRidge(const RidgelineDirection& ridgeData, const float increment);

    static void computeGroupParamFulfillment(std::vector<IHProtoData>* ihProtoData, const std::vector<bool>& modifiedByRidgeline);

    static inline QSharedPointer<tml::qtree<float, IHHeightBoundNode>> heightBoundsqtree = nullptr;
    static const inline QQuaternion rotateLeft90 = QQuaternion::fromEulerAngles(0, 90.0f, 0);
    static inline std::map<int, std::map<int, float>> ihMerges;
};