#pragma once
#include "../OmnigenGenerationStage.h"

namespace Generation
{
    template<EGenerationStage GS>
    class StageGen
    {
    public:
        // Prepare core data for this stage
        static void initialize() {};

        // Checks if stage may be autogenerated.
        // Only the Layout stage is expected to return false here.
        static constexpr bool hasAutoGen() { return true; }

        // Launch generation
        static bool autoGen() { return true; };

        // Remove all data related to this stage
        static void clear() {};

        // Check if all data of this stage is valid
        static bool validate() { return true; };

        // Run additional logic before moving to the next stage
        static void finalize() {};
    };

    enum class FStageStates
    {
        None = 0,
        HasDataToSave = 1 << 0,
        HasBeenInitialized = 1 << 1,
        HasBeenValidated = 1 << 2,
        HasBeenFinalized = 1 << 3,
    };
    DECLARE_FLAG_OPERATORS(FStageStates);

    // Flag for stage's data states
    template<EGenerationStage GS>
    struct StageTraits
    {
        static inline FStageStates state;
    };
    
}